--------------------------------------------------------
--  File created - Wednesday-March-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

--Here Nani is the database ..if you are using some XYZ database 
--please replace the same and import into  u r machine...

  CREATE TABLE "NANI"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(5,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"LAST_NAME" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"HIRE_DATE" DATE, 
	"JOB_ID" NUMBER, 
	"SALARY" NUMBER(8,2), 
	"MANAGER_ID" NUMBER DEFAULT NULL, 
	"DEPARTMENT_ID" NUMBER DEFAULT NULL
   -- FOREIGN KEY (job_id) REFERENCES jobs (job_id) ON DELETE CASCADE,
   -- FOREIGN KEY (department_id) REFERENCES departments (department_id) ON DELETE CASCADE,
   -- FOREIGN KEY (manager_id) REFERENCES employees (employee_id)

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NANI.EMPLOYEES
SET DEFINE OFF;
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (100,'Steven','King','steven.king@sqltutorial.org','515.123.4567',to_date('17-JUN-87','DD-MON-RR'),4,24000,null,9);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (101,'Neena','Kochhar','neena.kochhar@sqltutorial.org','515.123.4568',to_date('21-SEP-89','DD-MON-RR'),5,17000,100,9);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (102,'David','De Haan','lex.de haan@sqltutorial.org','515.123.4569',to_date('13-JAN-93','DD-MON-RR'),5,17000,100,9);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (103,'Nancy','Hunold','alexander.hunold@sqltutorial.org','590.423.4567',to_date('03-JAN-90','DD-MON-RR'),9,9000,102,6);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (104,'Bruce','Ernst','bruce.ernst@sqltutorial.org','590.423.4568',to_date('21-MAY-91','DD-MON-RR'),9,6000,103,6);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (105,'David','Austin','david.austin@sqltutorial.org','590.423.4569',to_date('25-JUN-97','DD-MON-RR'),9,4800,103,6);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (106,'Valli','Pataballa','valli.pataballa@sqltutorial.org','590.423.4560',to_date('05-FEB-98','DD-MON-RR'),9,4800,103,6);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (107,'David','Lorentz','diana.lorentz@sqltutorial.org','590.423.5567',to_date('07-FEB-99','DD-MON-RR'),9,4200,103,6);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (108,'Nancy','Greenberg','nancy.greenberg@sqltutorial.org','515.124.4569',to_date('17-AUG-94','DD-MON-RR'),7,12000,101,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (109,'Daniel','Faviet','daniel.faviet@sqltutorial.org','515.124.4169',to_date('16-AUG-94','DD-MON-RR'),6,9000,108,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (110,'John','Chen','john.chen@sqltutorial.org','515.124.4269',to_date('28-SEP-97','DD-MON-RR'),6,8200,108,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (111,'Ismael','Sciarra','ismael.sciarra@sqltutorial.org','515.124.4369',to_date('30-SEP-97','DD-MON-RR'),6,7700,108,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (112,'Jose Manuel','Urman','jose manuel.urman@sqltutorial.org','515.124.4469',to_date('07-MAR-98','DD-MON-RR'),6,7800,108,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (113,'Luis','Popp','luis.popp@sqltutorial.org','515.124.4567',to_date('07-DEC-99','DD-MON-RR'),6,6900,108,10);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (114,'Den','Raphaely','den.raphaely@sqltutorial.org','515.127.4561',to_date('07-DEC-94','DD-MON-RR'),14,11000,100,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (115,'Alexander','Khoo','alexander.khoo@sqltutorial.org','515.127.4562',to_date('18-MAY-95','DD-MON-RR'),13,3100,114,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (116,'Shelli','Baida','shelli.baida@sqltutorial.org','515.127.4563',to_date('24-DEC-97','DD-MON-RR'),13,2900,114,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (117,'David','Tobias','sigal.tobias@sqltutorial.org','515.127.4564',to_date('24-JUL-97','DD-MON-RR'),13,2800,114,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (118,'Guy','Himuro','guy.himuro@sqltutorial.org','515.127.4565',to_date('15-NOV-98','DD-MON-RR'),13,2600,114,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (119,'Karen','Colmenares','karen.colmenares@sqltutorial.org','515.127.4566',to_date('10-AUG-99','DD-MON-RR'),13,2500,114,3);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (120,'Matthew','Weiss','matthew.weiss@sqltutorial.org','650.123.1234',to_date('18-JUL-96','DD-MON-RR'),19,8000,100,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (121,'Nancy','Fripp','adam.fripp@sqltutorial.org','650.123.2234',to_date('10-APR-97','DD-MON-RR'),19,8200,100,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (122,'Payam','Kaufling','payam.kaufling@sqltutorial.org','650.123.3234',to_date('01-MAY-95','DD-MON-RR'),19,7900,100,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (123,'Nancy','Vollman','shanta.vollman@sqltutorial.org','650.123.4234',to_date('10-OCT-97','DD-MON-RR'),19,6500,100,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (126,'Irene','Mikkilineni','irene.mikkilineni@sqltutorial.org','650.124.1224',to_date('28-SEP-98','DD-MON-RR'),18,2700,120,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (145,'John','Russell','john.russell@sqltutorial.org',null,to_date('01-OCT-96','DD-MON-RR'),15,14000,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (146,'Karen','Partners','karen.partners@sqltutorial.org',null,to_date('05-JAN-97','DD-MON-RR'),15,13500,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (176,'Jonathon','Taylor','jonathon.taylor@sqltutorial.org',null,to_date('24-MAR-98','DD-MON-RR'),16,8600,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (177,'Jack','Livingston','jack.livingston@sqltutorial.org',null,to_date('23-APR-98','DD-MON-RR'),16,8400,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (178,'Kimberely','Grant','kimberely.grant@sqltutorial.org',null,to_date('24-MAY-99','DD-MON-RR'),16,7000,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (179,'Charles','Johnson','charles.johnson@sqltutorial.org',null,to_date('04-JAN-00','DD-MON-RR'),16,6200,100,8);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (192,'Sarah','Bell','sarah.bell@sqltutorial.org','650.501.1876',to_date('04-FEB-96','DD-MON-RR'),17,4000,123,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (193,'Nancy','Everett','britney.everett@sqltutorial.org','650.501.2876',to_date('03-MAR-97','DD-MON-RR'),17,3900,123,5);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (200,'Jennifer','Whalen','jennifer.whalen@sqltutorial.org','515.123.4444',to_date('17-SEP-87','DD-MON-RR'),3,4400,101,1);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (201,'Michael','Hartstein','michael.hartstein@sqltutorial.org','515.123.5555',to_date('17-FEB-96','DD-MON-RR'),10,13000,100,2);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (202,'Pat','Fay','pat.fay@sqltutorial.org','603.123.6666',to_date('17-AUG-97','DD-MON-RR'),11,6000,201,2);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (203,'Susan','Mavris','susan.mavris@sqltutorial.org','515.123.7777',to_date('07-JUN-94','DD-MON-RR'),8,6500,101,4);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (204,'Hermann','Baer','hermann.baer@sqltutorial.org','515.123.8888',to_date('07-JUN-94','DD-MON-RR'),12,10000,101,7);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (205,'Shelley','Higgins','shelley.higgins@sqltutorial.org','515.123.8080',to_date('07-JUN-94','DD-MON-RR'),2,12000,101,11);
Insert into NANI.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,MANAGER_ID,DEPARTMENT_ID) values (206,'William','Gietz','william.gietz@sqltutorial.org','515.123.8181',to_date('07-JUN-94','DD-MON-RR'),1,8300,205,11);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "NANI"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "NANI"."EMPLOYEES" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "NANI"."EMPLOYEES" MODIFY ("HIRE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "NANI"."EMPLOYEES" MODIFY ("JOB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NANI"."EMPLOYEES" MODIFY ("SALARY" NOT NULL ENABLE);
